### PR TITLE
fix: add resource limit in worker.js (CWE-770)

### PR DESCRIPTION
**Pull request by anupamme**
The request.json() calls at all four entry points lack explicit request body size limits. An attacker can send extremely large JSON payloads to exhaust memory and CPU resources, causing denial of service. Cloudflare Workers and Vercel Edge Functions have platform-level limits, but the application does not implement application-layer size validation before parsing JSON. The affected code is `worker.js:450`, and this change addresses it.

Reference: [CWE-770](https://cwe.mitre.org/data/definitions/770.html)

## What changed
- `worker.js`
- `api/index.js`

## Verification
No automated check could be run against this repository, so this change is unverified beyond review. Please treat it as a suggestion.

### CODE REVIEW

**Comment by pingmike2** [comment]
感谢提交。经评估不合并：

1. 该检查仅读 `Content-Length` 头——不发该头的 chunked 请求完全绕过，防护形同虚设；
2. Workers/Vercel Edge 平台本身已有请求体上限（Cloudflare 100MB、Vercel 4.5MB），且 `request.json()` 解析失败本就有 400 兜底；
3. 本服务是个人自用网关，前置 API Key 鉴权，攻击面有限。

如未来需要真实限制，应在读取流时按实际字节数截断，而非信任请求头。

**Comment by anupamme** [comment]
Thanks for the detailed review. I agree that the current implementation is incomplete because it relies on Content-Length, which can be omitted and therefore doesn’t provide a true application-layer byte limit.

The intent was to prevent request.json() from parsing unexpectedly large bodies, but I agree that a proper mitigation should enforce the limit while consuming `request.body`, rather than trusting the header.

Given the platform-level request limits and the API-key requirement, I understand why you don’t consider the current issue actionable for this deployment. I’ll close this out rather than defend the current patch.

If there’s interest later, I can submit a smaller follow-up implementing a stream-based limit that works independently of Content-Length.
